# Offense count: 74
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 17

# Offense count: 1
RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'lib/fxdatapi/auth.rb'

# Offense count: 12
# Configuration parameters: .
# SupportedStyles: have_received, receive
RSpec/MessageSpies:
  EnforcedStyle: receive

# Offense count: 115
RSpec/MultipleExpectations:
  Max: 15

# Offense count: 372
# Configuration parameters: EnforcedStyle, IgnoreSharedExamples.
# SupportedStyles: always, named_only
RSpec/NamedSubject:
  Enabled: false

# Offense count: 16
RSpec/SubjectStub:
  Exclude:
    - 'lib/fxdatapi/convert_all.rb'
    - 'lib/fxdatapi/convert.rb'
    - 'lib/fxdatapi/currencies.rb'
    - 'lib/fxdatapi/daily_average.rb'
    - 'lib/fxdatapi/historical.rb'
    - 'lib/fxdatapi/margins_spreads.rb'
    - 'lib/fxdatapi/performances.rb'
    - 'lib/fxdatapi/signals.rb'
    - 'lib/fxdatapi/version.rb'
    - 'lib/fxdatapi/weekly_average.rb'
    - 'lib/fxdatapi/monthly_average.rb'

# Offense count: 69
# Configuration parameters: AllowedConstants.
Style/Documentation:
  Enabled: false